---
web_app_name: infoservice
web_app_image: "{{ dockerhub_username }}/{{ web_app_name }}"
web_app_tag: python-latest
web_app_internal_port: 8000
web_app_port: 5000
web_app_addr: 127.0.0.1
web_app_external_port: 8000
web_app_port_mapping: "{{ web_app_addr }}:{{ web_app_port }}:{{ web_app_internal_port }}"
web_app_container_name: Xantusia
web_app_dir: "/opt/{{ web_app_name }}"
web_app_wipe: false
