---
app_name: infoservice
docker_image: "{{ dockerhub_username }}/{{ app_name }}"
docker_tag: python-latest
app_internal_port: 8000
app_port: 5000
local_addr: 127.0.0.1
external_port: 8000
port_mapping: "{{ local_addr }}:{{ app_port }}:{{ app_internal_port }}"
app_container_name: Xantusia

compose_project_dir: "/opt/{{ app_name }}"
web_app_wipe: false
