apiVersion: apps/v1
kind: Deployment
metadata:
  name: infoservices
  labels:
    app: Infoservice

spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  replicas: 5
  selector:
    matchLabels:
      app: Infoservice

  template:
    metadata:
      labels:
        app: Infoservice
    spec:
      containers:
      - name: infoservice
        image: ub3rch/infoservice:go-latest
        imagePullPolicy: "Always"

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
