---
- name: Provision web servers
  hosts: webservers
  become: yes

  roles:
    - role: common
      become: true
      tags:
        - common

    - role: docker
      become: true
      tags:
        - docker

