---
- name: Docker install
  tags:
    - docker_install
    - packages

  block:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        state: present

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ docker_ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present

  rescue:
    - name: Handle failure
      ansible.builtin.apt:
        update_cache: true

  always:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Log service status
      ansible.builtin.debug:
        var: ansible_facts.services['docker'].state


- name: Configure Docker
  tags:
    - docker_config
    - users

  block:
    - name: Create Docker Group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: user
        groups: docker
        append: true
        state: present

    - name: Log failure
      ansible.builtin.debug:
        msg: "Docker configuration successfull"

  rescue:
    - name: Log failure
      ansible.builtin.debug:
        msg: "Docker configuration failed"

  always:
    - name: Log failure
      ansible.builtin.debug:
        msg: "Docker configuration finished"
