---
- name: Docker install
  block:
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
      notify: restart docker

  rescue:
    - name: Handle failure
      apt:
        update_cache: yes

  always:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Log service status
      debug:
        var: ansible_facts.services['docker'].state

  tags:
    - docker_install
    - packages

- name: Configure Docker
  block:
    - name: Create Docker Group
      group:
        name: docker
        state: present

    - name: Add user to Docker group
      user:
        name: user
        groups: docker
        append: yes
        state: present

    - name: Log failure
      debug:
        msg: "Docker configuration successfull"

  rescue:
    - name: Log failure
      debug:
        msg: "Docker configuration failed"

  always:
    - name: Log failure
      debug:
        msg: "Docker configuration finished"

  tags:
    - docker_config
    - users
